[build]
  base = "web"
  command = "npm run build"
  publish = "web/dist"

[build.environment]
  VITE_MMT_TYPST_ROOT = "https://eo.xiyihan.cn/typst_sandbox"
  VITE_MMT_PACK_FETCH_URL = "https://eo.xiyihan.cn/typst_sandbox/pack-v2/ba"
  VITE_MMT_PACK_BASE = "https://eo.xiyihan.cn/typst_sandbox"
