[package]
name = "mmt_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "mmt_rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.17"
winnow = "0.7.14"
